"""MV2-12 — Matriz objetiva de dados faltantes.

Transforma o bloqueio genérico "faltam dados" numa matriz com prioridade, fonte
provável, gate/dia desbloqueado e próxima ação. Cruza:
  - MV2-10 (mv2_10_external_data_backlog.csv, mv2_10_gap_matrix.csv) — presentes localmente;
  - MV2-11 (fatos consolidados em mv2_12_data_readiness_common.MV2_11_FACTS);
  - varredura local real (mv2_12_local_recovery_candidates.csv) — se já gerada.

Cada linha é validada contra as taxonomias obrigatórias de status e finalidade.
Nenhum dado crítico é marcado como resolvido sem path, hash, fonte ou justificativa.

Saída: outputs_public/mv2_data_readiness/mv2_12_missing_data_matrix.csv
"""

from __future__ import annotations

from pathlib import Path

from mv2_12_data_readiness_common import (
    MV2_10_EXTERNAL_BACKLOG,
    MV2_10_GAP_MATRIX,
    OUTPUT_DIR,
    PROJECT_ROOT,
    ensure_output_dir,
    read_csv_rows,
    validate_purpose,
    validate_status,
    write_csv,
)

COLUMNS = [
    "missing_data_id",
    "data_name",
    "region",
    "related_patch_id",
    "related_asset_id",
    "related_event_id",
    "current_status",
    "scientific_purpose",
    "unlocks_day",
    "unlocks_gate",
    "required_format",
    "expected_location",
    "known_source_or_portal",
    "local_search_result",
    "external_download_needed",
    "manual_action_needed",
    "can_be_done_now",
    "priority",
    "blocking_reason",
    "notes",
]

# Matriz curada — derivada da auditoria MV2-10 + programação MV2-11 + varredura local.
# external_download_needed / manual_action_needed / can_be_done_now são strings
# "true"/"false". current_status e scientific_purpose seguem as taxonomias MV2-12.
MISSING_DATA: list[dict[str, str]] = [
    # ---------------- P0: destrava o maior número de gates ----------------
    {
        "missing_data_id": "MD_P0_01_SCENE_ID",
        "data_name": "scene_id / product_id dos 128 exports GEE/Sentinel",
        "region": "Todas",
        "related_patch_id": "128_patches",
        "related_asset_id": "128_assets",
        "related_event_id": "",
        "current_status": "FALTANTE_RECUPERAR_LOCAL",
        "scientific_purpose": "SCENE_LINEAGE|TEMPORALIDADE|REPRODUTIBILIDADE",
        "unlocks_day": "DIA_02|DIA_03",
        "unlocks_gate": "G1",
        "required_format": "log/CSV de tasks GEE ou metadados de exportação",
        "expected_location": "histórico de tasks GEE da usuária / workspace PROJETO",
        "known_source_or_portal": "Google Earth Engine task history",
        "local_search_result": "AUSENTE — 0 scene_id nos 128 assets do manifesto MV2-03",
        "external_download_needed": "false",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P0",
        "blocking_reason": "sem scene_id não há acquisition_datetime, cloud_cover, lineage nem Trilha A",
        "notes": "uma única recuperação destrava datetime+cloud_cover+lineage da Trilha A inteira",
    },
    {
        "missing_data_id": "MD_P0_02_ACQ_DATETIME",
        "data_name": "acquisition_datetime por asset/patch",
        "region": "Todas",
        "related_patch_id": "128_patches",
        "related_asset_id": "128_assets",
        "related_event_id": "",
        "current_status": "PRESENTE_SEM_METADATA",
        "scientific_purpose": "TEMPORALIDADE",
        "unlocks_day": "DIA_02",
        "unlocks_gate": "G2",
        "required_format": "campo datetime ISO por asset",
        "expected_location": "manifesto temporal MV2-02 (campos hoje null)",
        "known_source_or_portal": "derivável do scene_id (MD_P0_01)",
        "local_search_result": "TODOS_NULOS — 0/128 com datetime válido",
        "external_download_needed": "false",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P0",
        "blocking_reason": "datetime ausente; não inferir por nome de arquivo sem evidência forte",
        "notes": "depende de MD_P0_01; não inferir data por filename",
    },
    {
        "missing_data_id": "MD_P0_03_CLOUD_COVER",
        "data_name": "cloud_cover por asset/patch",
        "region": "Todas",
        "related_patch_id": "128_patches",
        "related_asset_id": "128_assets",
        "related_event_id": "",
        "current_status": "PRESENTE_SEM_METADATA",
        "scientific_purpose": "CLOUD_COVER",
        "unlocks_day": "DIA_03",
        "unlocks_gate": "G2",
        "required_format": "fração de nuvem por patch (0-1)",
        "expected_location": "metadados GEE/Copernicus por cena",
        "known_source_or_portal": "Copernicus Hub / GEE asset metadata",
        "local_search_result": "AUSENTE — 162/164 patches sem cloud_cover",
        "external_download_needed": "false",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P0",
        "blocking_reason": "confound visual do encoder não controlável sem cloud_cover",
        "notes": "derivável se scene_id recuperado (MD_P0_01)",
    },
    {
        "missing_data_id": "MD_P0_04_PNG_RECIFE",
        "data_name": "PNG canônicos de Recife com vínculo patch_id (deficit ~35)",
        "region": "Recife",
        "related_patch_id": "REC_patches",
        "related_asset_id": "REC_assets",
        "related_event_id": "",
        "current_status": "FALTANTE_RECUPERAR_LOCAL",
        "scientific_purpose": "REBALANCEAMENTO_REGIONAL",
        "unlocks_day": "DIA_08",
        "unlocks_gate": "G_COVERAGE",
        "required_format": "PNG renderizado com patch_id/asset_id rastreável",
        "expected_location": "workspace PROJETO (read-only) / local_runs",
        "known_source_or_portal": "exportação canônica PROJETO",
        "local_search_result": "PARCIAL — 102 candidatos Recife LOW sem vínculo patch/asset (MV2-11)",
        "external_download_needed": "false",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P0",
        "blocking_reason": "cobertura Recife=5.4%; 131 candidatos LOW não canonizáveis sem vínculo forte",
        "notes": "candidato regional != canônico; só promover com patch_id/asset_id forte",
    },
    {
        "missing_data_id": "MD_P0_05_PNG_PETROPOLIS",
        "data_name": "PNG canônicos de Petrópolis com vínculo patch_id (deficit ~45)",
        "region": "Petropolis",
        "related_patch_id": "PET_patches",
        "related_asset_id": "PET_assets",
        "related_event_id": "",
        "current_status": "FALTANTE_RECUPERAR_LOCAL",
        "scientific_purpose": "REBALANCEAMENTO_REGIONAL",
        "unlocks_day": "DIA_08",
        "unlocks_gate": "G_COVERAGE",
        "required_format": "PNG renderizado com patch_id/asset_id rastreável",
        "expected_location": "workspace PROJETO (read-only) / local_runs",
        "known_source_or_portal": "exportação canônica PROJETO",
        "local_search_result": "PARCIAL — 29 candidatos Petropolis LOW sem vínculo patch/asset (MV2-11)",
        "external_download_needed": "false",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P0",
        "blocking_reason": "cobertura Petropolis=6.25%; Petrópolis é cohort mass_movement separado de flood",
        "notes": "não misturar Petrópolis (mass_movement) com flood em nenhuma análise",
    },
    {
        "missing_data_id": "MD_P0_06_RASTER_ESPECTRAL",
        "data_name": "Raster Sentinel-2 L2A espectral nativo (bandas B02/B03/B04/B08/B11/B12 + SCL)",
        "region": "Todas",
        "related_patch_id": "128_patches",
        "related_asset_id": "128_assets",
        "related_event_id": "",
        "current_status": "FALTANTE_BAIXAR_EXTERNO",
        "scientific_purpose": "RASTER_SENTINEL_ESPECTRAL",
        "unlocks_day": "DIA_10",
        "unlocks_gate": "G1",
        "required_format": "GeoTIFF/JP2/SAFE multibanda com CRS",
        "expected_location": "data_quarantine/mv2_12_intake ou external_data_local/mv2_12 (git-ignored)",
        "known_source_or_portal": "https://dataspace.copernicus.eu / GEE export",
        "local_search_result": "AUSENTE — 0 GeoTIFF/JP2/SAFE espectral legível na varredura MV2-12",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P0",
        "blocking_reason": "PNG/NPZ/DINOv2 visual não substituem raster espectral; 0 raster nativo local",
        "notes": "depende de MD_P0_01 (scene_id) para download auditável por patch",
    },
    # ---------------- P1: fechamento observacional ----------------
    {
        "missing_data_id": "MD_P1_07_FOOTPRINT_RECIFE",
        "data_name": "Footprint vetorial de inundação Recife mai/2022 (Charter758/EMSR601)",
        "region": "Recife",
        "related_patch_id": "REC_00019",
        "related_asset_id": "",
        "related_event_id": "REC_2022_05_24_30",
        "current_status": "FALTANTE_DIGITALIZAR",
        "scientific_purpose": "GEOMETRIA_EVENTO|EVIDENCIA_OBSERVACIONAL",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G2|G3",
        "required_format": "GeoJSON/SHP polígono com CRS e incerteza",
        "expected_location": "datasets/external_sources/recife_minimal_tp/.../charter758/derived",
        "known_source_or_portal": "Copernicus EMS EMSR601 (vetor pago) / digitalização do PNG",
        "local_search_result": "PNG_PRESENTE_VETOR_AUSENTE — candidato digitalizado tem 0 features",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "true",
        "priority": "P1",
        "blocking_reason": "só raster PNG disponível; vetor oficial exige acesso pago/institucional",
        "notes": "única evidência observacional digitalizável agora; só imagem != vetor fechado",
    },
    {
        "missing_data_id": "MD_P1_08_GEOM_EVENTOS_PROTOCOLO_C",
        "data_name": "Geometrias dos 9 eventos candidatos do Protocolo C",
        "region": "Todas",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "9_eventos_v2aq",
        "current_status": "FALTANTE_DIGITALIZAR",
        "scientific_purpose": "GEOMETRIA_EVENTO|OVERLAY_PATCH_EVENTO",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G4",
        "required_format": "GeoJSON polígono observado com CRS, fonte e data",
        "expected_location": "docs/protocolo_c/v2aq_event_geometry_patch_link/geojson_candidates",
        "known_source_or_portal": "mapas oficiais / Defesa Civil / Copernicus EMS",
        "local_search_result": "TODOS_NULL — 9/9 geometry=null (4 textual, 4 mapa, 1 insuficiente)",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P1",
        "blocking_reason": "geometry=null; município inteiro não é geometria de evento observado",
        "notes": "G4 permanece bloqueado; ver mv2_12_event_geometry_backlog.csv",
    },
    {
        "missing_data_id": "MD_P1_09_DEFESA_CIVIL_RECIFE",
        "data_name": "Pontos GPS de vistoria Defesa Civil Recife mai/2022 (400 pontos)",
        "region": "Recife",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "REC_2022_05_24_30",
        "current_status": "PRESENTE_SEM_VINCULO_FORTE",
        "scientific_purpose": "GEOMETRIA_EVENTO|EVIDENCIA_OBSERVACIONAL",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G2|G3",
        "required_format": "CSV lat/lon ou shapefile revisado",
        "expected_location": "quarentena local (GeoJSON existente is_reviewed=false)",
        "known_source_or_portal": "Defesa Civil Recife (LAI/email)",
        "local_search_result": "PARCIAL — 400 pontos existem mas conflitam com Charter758 (v2bs); não revisados",
        "external_download_needed": "false",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P1",
        "blocking_reason": "conflito espacial documentado; exige revisão humana para escolher geometria",
        "notes": "ponto != footprint; não promover a GT sem revisão",
    },
    {
        "missing_data_id": "MD_P1_10_CEMADEN",
        "data_name": "Série de alertas/relatórios CEMADEN por evento",
        "region": "Todas",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "REC/PET/CTB",
        "current_status": "FALTANTE_PORTAL_MANUAL",
        "scientific_purpose": "EVIDENCIA_OBSERVACIONAL|TEMPORALIDADE",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G4|G5",
        "required_format": "CSV/PDF de alertas por estação e data",
        "expected_location": "quarentena local após solicitação",
        "known_source_or_portal": "https://www.cemaden.gov.br/ (LAI 12.527/2011)",
        "local_search_result": "BLOQUEADO — exige solicitação formal; cartas criadas em v2bk",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P1",
        "blocking_reason": "dados históricos detalhados exigem LAI; prazo legal 30 dias",
        "notes": "confirmação temporal independente; não cria label",
    },
    {
        "missing_data_id": "MD_P1_11_APAC",
        "data_name": "Série pluviométrica/alertas APAC Recife 2022",
        "region": "Recife",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "REC_2022_05_24_30",
        "current_status": "PRESENTE_SEM_METADATA",
        "scientific_purpose": "EVIDENCIA_OBSERVACIONAL|TEMPORALIDADE",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G4",
        "required_format": "CSV série por estação",
        "expected_location": "quarentena local (PDF informativo já baixado CONTEXT_ONLY)",
        "known_source_or_portal": "https://www.apac.pe.gov.br/",
        "local_search_result": "PARCIAL — PDF baixado; série por estação não pública",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P1",
        "blocking_reason": "série por estação requer contato direto com APAC",
        "notes": "contexto != geometria de evento",
    },
    {
        "missing_data_id": "MD_P1_12_ANA_HIDROWEB",
        "data_name": "Série hidrométrica Capibaribe estação 39187800 (Recife)",
        "region": "Recife",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "REC_2022_05_24_30",
        "current_status": "PRESENTE_SEM_METADATA",
        "scientific_purpose": "EVIDENCIA_OBSERVACIONAL|TEMPORALIDADE",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G4",
        "required_format": "CSV série diária/horária 2022",
        "expected_location": "quarentena local (download anterior veio vazio)",
        "known_source_or_portal": "https://www.snirh.gov.br/hidroweb/",
        "local_search_result": "BAIXADO_VAZIO — estação sem dados 2022 no download realizado",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "true",
        "priority": "P1",
        "blocking_reason": "consulta anterior retornou vazia; tentar tipo diário/intervalo explícito",
        "notes": "prova hidrométrica independente; ausência de dado != ausência de evento",
    },
    {
        "missing_data_id": "MD_P1_13_DRM_RJ",
        "data_name": "Mapeamento de cicatrizes DRM-RJ Petrópolis fev/2022",
        "region": "Petropolis",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "PET_2022_02_15",
        "current_status": "FALTANTE_PORTAL_MANUAL",
        "scientific_purpose": "GEOMETRIA_EVENTO|EVIDENCIA_OBSERVACIONAL",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G2|G3",
        "required_format": "SHP/GeoJSON de cicatrizes de movimento de massa",
        "expected_location": "quarentena local após acesso",
        "known_source_or_portal": "http://www.drm.rj.gov.br/",
        "local_search_result": "AUSENTE — DRM-RJ não acessado",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P1",
        "blocking_reason": "fonte não acessada; cohort mass_movement separado de flood",
        "notes": "massa != inundação; manter coortes separados",
    },
    {
        "missing_data_id": "MD_P1_14_DEFESA_CIVIL_CURITIBA",
        "data_name": "Ocorrências/geometria inundação Curitiba jan/2022",
        "region": "Curitiba",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "CTB_2022_01_15_16",
        "current_status": "FALTANTE_PORTAL_MANUAL",
        "scientific_purpose": "GEOMETRIA_EVENTO|EVIDENCIA_OBSERVACIONAL",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G2|G3",
        "required_format": "CSV pontos / GeoJSON polígono com CRS",
        "expected_location": "quarentena local após solicitação",
        "known_source_or_portal": "https://geocuritiba.ippuc.org.br/ / Defesa Civil CTB",
        "local_search_result": "AUSENTE — deep crawl v2ce 181 links, 0 geometria; dossiê criado",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P1",
        "blocking_reason": "0 geometria pública em 1 hop; solicitação formal pronta (v2ce)",
        "notes": "cadeia v2ca-v2cg roda automaticamente quando dado válido chegar ao intake",
    },
    {
        "missing_data_id": "MD_P1_15_SENTINEL1_SAR",
        "data_name": "Imagens SAR Sentinel-1 pré/pós evento (detecta água sob nuvem)",
        "region": "Todas",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "REC/PET/CTB",
        "current_status": "FALTANTE_BAIXAR_EXTERNO",
        "scientific_purpose": "EVIDENCIA_OBSERVACIONAL|RASTER_SENTINEL_ESPECTRAL",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G2|G3",
        "required_format": "GRD backscatter GeoTIFF",
        "expected_location": "data_quarantine/mv2_12_intake (git-ignored)",
        "known_source_or_portal": "https://dataspace.copernicus.eu",
        "local_search_result": "AUSENTE — 0 assets SAR no manifesto",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P1",
        "blocking_reason": "nenhum asset SAR; requer processamento de backscatter",
        "notes": "supera bloqueio de nuvem em dado óptico; SAR != Sentinel-2 espectral",
    },
    {
        "missing_data_id": "MD_P1_16_DIGITALIZACAO_BOUNDARIES_RECIFE",
        "data_name": "Boundaries vetoriais reais dos 36 patches Recife restantes",
        "region": "Recife",
        "related_patch_id": "REC_36_patches",
        "related_asset_id": "",
        "related_event_id": "",
        "current_status": "FALTANTE_DIGITALIZAR",
        "scientific_purpose": "OVERLAY_PATCH_EVENTO",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "G3",
        "required_format": "GeoJSON polígono por patch com CRS",
        "expected_location": "datasets/external_sources/recife_minimal_tp/derived",
        "known_source_or_portal": "workspace PROJETO / digitalização",
        "local_search_result": "PARCIAL — só REC_00019 tem geometria real; 36 são bounds estimados",
        "external_download_needed": "false",
        "manual_action_needed": "true",
        "can_be_done_now": "true",
        "priority": "P1",
        "blocking_reason": "36 boundaries = reprojected_bounds_estimated, não digitalizadas",
        "notes": "overlay confiável só para REC_00019 hoje",
    },
    # ---------------- P2: preparação futura (apenas requisitos) ----------------
    {
        "missing_data_id": "MD_P2_17_DADOS_NEGATIVOS_FORMAIS",
        "data_name": "Dados para negativos formais (matched negatives) — apenas requisitos",
        "region": "Todas",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "",
        "current_status": "NAO_NECESSARIO_AGORA",
        "scientific_purpose": "NEGATIVO_FORMAL",
        "unlocks_day": "DIA_21",
        "unlocks_gate": "G6",
        "required_format": "registro de não-ocorrência documentada por fonte independente",
        "expected_location": "—",
        "known_source_or_portal": "CEMADEN/ANA (janela sem evento confirmada)",
        "local_search_result": "NAO_CRIAR_AGORA — apenas registrar requisitos",
        "external_download_needed": "false",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P2",
        "blocking_reason": "ausência de evidência != negativo; exige não-ocorrência documentada",
        "notes": "requisitos: mesma cidade/região comparável; janela temporal compatível; asset Sentinel equivalente; ausência observacional documentada; distância espaço-temporal controlada; sem sobreposição com evento",
    },
    {
        "missing_data_id": "MD_P2_18_CAMPOS_SPLIT_ANTI_LEAKAGE",
        "data_name": "Campos mínimos para split anti-leakage",
        "region": "Todas",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "",
        "current_status": "PRESENTE_SEM_METADATA",
        "scientific_purpose": "SPLIT_ANTI_LEAKAGE",
        "unlocks_day": "DIA_21",
        "unlocks_gate": "G7",
        "required_format": "campos: city,event_id,scene_id,acquisition_datetime,patch_geometry,spatial_group,source_asset,render_origin,duplicated_visual_source",
        "expected_location": "manifesto de corpus (a consolidar)",
        "known_source_or_portal": "derivável de MD_P0_01..06 + geometria",
        "local_search_result": "PARCIAL — city e spatial_group existem; scene_id/datetime/patch_geometry faltam",
        "external_download_needed": "false",
        "manual_action_needed": "false",
        "can_be_done_now": "false",
        "priority": "P2",
        "blocking_reason": "split treinável não pode existir enquanto silver formal=0",
        "notes": "não criar split treinável agora; só mapear campos faltantes",
    },
    {
        "missing_data_id": "MD_P2_19_CONTEXTO_TERRITORIAL",
        "data_name": "Camadas de contexto territorial (IBGE grade 1km, MapBiomas, SGB/CPRM, PE3D/MDE)",
        "region": "Todas",
        "related_patch_id": "",
        "related_asset_id": "",
        "related_event_id": "",
        "current_status": "FALTANTE_PORTAL_MANUAL",
        "scientific_purpose": "CONTEXTO_TERRITORIAL|REPRODUTIBILIDADE",
        "unlocks_day": "DIA_18",
        "unlocks_gate": "probe_externo",
        "required_format": "raster/vetor de contexto com licença verificada",
        "expected_location": "external_data_local/mv2_12 (git-ignored)",
        "known_source_or_portal": "IBGE / MapBiomas / SGB-CPRM / PE3D",
        "local_search_result": "PARCIAL — XLSX/PDF de contexto baixados; rasters por patch não",
        "external_download_needed": "true",
        "manual_action_needed": "true",
        "can_be_done_now": "false",
        "priority": "P2",
        "blocking_reason": "licença IBGE grade 1km a reverificar; raster MapBiomas via GEE",
        "notes": "contexto/confounder, não evento; não vira label",
    },
]


def _augment_from_mv2_10() -> int:
    """Confere que a matriz cobre os bloqueadores externos do MV2-10 (cross-check)."""
    ext = read_csv_rows(MV2_10_EXTERNAL_BACKLOG)
    gap = read_csv_rows(MV2_10_GAP_MATRIX)
    return len(ext) + len(gap)


def build_rows() -> list[dict[str, str]]:
    for row in MISSING_DATA:
        validate_status(row["current_status"])
        validate_purpose(row["scientific_purpose"])
        # Trava: nada crítico (P0/P1) pode ser marcado resolvido sem evidência.
        if row["priority"] in {"P0", "P1"} and row["current_status"] == "PRESENTE_VALIDADO":
            if not (row["expected_location"] and row["local_search_result"]):
                raise ValueError(
                    f"{row['missing_data_id']}: PRESENTE_VALIDADO exige location e evidência"
                )
    return MISSING_DATA


def main() -> None:
    ensure_output_dir()
    rows = build_rows()
    cross = _augment_from_mv2_10()
    out = OUTPUT_DIR / "mv2_12_missing_data_matrix.csv"
    write_csv(out, COLUMNS, rows)
    p0 = sum(1 for r in rows if r["priority"] == "P0")
    p1 = sum(1 for r in rows if r["priority"] == "P1")
    p2 = sum(1 for r in rows if r["priority"] == "P2")
    print(f"[mv2_12_matrix] linhas: {len(rows)} (P0={p0} P1={p1} P2={p2})")
    print(f"[mv2_12_matrix] cross-check MV2-10 (ext+gap rows lidas): {cross}")
    print(f"[mv2_12_matrix] saida: {Path(out).relative_to(PROJECT_ROOT).as_posix()}")


if __name__ == "__main__":
    main()
