allowed_domains:
  - curitiba.pr.gov.br
  - dadosabertos.curitiba.pr.gov.br
  - defesacivil.pr.gov.br
  - geocuritiba.ippuc.org.br
  - ippuc.org.br
  - portal.inmet.gov.br
  - www.ana.gov.br
  - www.curitiba.pr.gov.br
  - www.defesacivil.pr.gov.br
  - www.gov.br
  - www.sgb.gov.br
  - www.simepar.br
